import { defineArrayMember, defineField, defineType } from "sanity";

/** Mirrors serviceSchema in src/lib/content/schemas.ts — PRD section 14. */
export const service = defineType({
  name: "service",
  title: "Service",
  type: "document",
  groups: [
    { name: "content", default: true },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "slug",
      type: "slug",
      options: { source: "h1", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "group",
      type: "string",
      group: "content",
      options: {
        list: [
          "strategy-and-design",
          "application-engineering",
          "ai-and-integration",
          "cloud-and-modernization",
          "quality-and-support",
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "h1", type: "string", group: "content", validation: (rule) => rule.required().min(5).max(80) }),
    defineField({
      name: "lead",
      type: "text",
      group: "content",
      rows: 5,
      description: "50-90 word lead, enforced by scripts/validate-content.ts.",
      validation: (rule) => rule.required().min(240).max(900),
    }),
    defineField({ name: "seo", type: "seo", group: "seo", validation: (rule) => rule.required() }),
    defineField({
      name: "businessProblems",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(3),
    }),
    defineField({
      name: "goodFit",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(2),
    }),
    defineField({
      name: "poorFit",
      title: "Poor fit",
      description: "Section 14 requires honest poor-fit cases, not just a sales list.",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(2),
    }),
    defineField({
      name: "sections",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "section" })],
      validation: (rule) => rule.required().min(3),
    }),
    defineField({
      name: "capabilities",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(4),
    }),
    defineField({
      name: "deliverables",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(3),
    }),
    defineField({
      name: "architectureDecisions",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(2),
    }),
    defineField({
      name: "securityNotes",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "integrations",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "scheduleDrivers",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(2),
    }),
    defineField({
      name: "engagementNote",
      type: "text",
      group: "content",
      rows: 3,
      validation: (rule) => rule.required().min(60),
    }),
    defineField({
      name: "exampleWorkflow",
      type: "illustration",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "evidence",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "evidence" })],
    }),
    defineField({
      name: "faqs",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "faq" })],
      validation: (rule) => rule.required().min(4).max(6),
    }),
    defineField({
      name: "related",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "link" })],
      validation: (rule) => rule.required().min(2).max(4),
    }),
    defineField({
      name: "cta",
      type: "object",
      group: "content",
      fields: [defineField({ name: "label", type: "string", validation: (rule) => rule.required().min(4).max(48) })],
      validation: (rule) => rule.required(),
    }),
  ],
  preview: { select: { title: "h1", subtitle: "group" } },
});
